external_url: https://ci.embassy.dev
data_dir: data
listen_port: 8000
image: embassy.dev/ci:latest
github:
  webhook_secret: asdfasdfasdfasdfasdfasdfasdfasfd
  app_id: 4321234
  private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    ....
    -----END RSA PRIVATE KEY-----